/* Generated By:JavaCC: Do not edit this line. OXPathScripterTreeConstants.java Version 5.0 */
package uk.ac.ox.comlab.oxpath.scriptParser;

public interface OXPathScripterTreeConstants
{
  public int JJTSCRIPT = 0;
  public int JJTDECLARATIONS = 1;
  public int JJTXQDECLARATIONS = 2;
  public int JJTVOID = 3;
  public int JJTDATABASEFILENAME = 4;
  public int JJTLETTER = 5;
  public int JJTURLNAME = 6;
  public int JJTSUPPORTEDPROTOCOLS = 7;
  public int JJTHOSTPORT = 8;
  public int JJTHOST = 9;
  public int JJTHOSTNAME = 10;
  public int JJTURLIALPHA = 11;
  public int JJTURLXALPHAS = 12;
  public int JJTURLXALPHA = 13;
  public int JJTURLSAFE = 14;
  public int JJTURLEXTRA = 15;
  public int JJTURLESCAPE = 16;
  public int JJTHOSTNUMBER = 17;
  public int JJTDIGITS = 18;
  public int JJTPORT = 19;
  public int JJTURLPATH = 20;
  public int JJTURLSEGMENT = 21;
  public int JJTURLSEARCH = 22;
  public int JJTVARIABLEDECLARATION = 23;
  public int JJTVARIABLENAME = 24;
  public int JJTPATHDECLARATION = 25;
  public int JJTOXPATHPATHSEGMENT = 26;
  public int JJTRELATIVEOXPATHLOCATIONPATH = 27;
  public int JJTDESCENDANTORSELFSHORT = 28;
  public int JJTOXPATHKLEENESTAR = 29;
  public int JJTOXPATHKLEENESTARPREDICATE = 30;
  public int JJTOXPATHKLEENESTARPREDICATEARG = 31;
  public int JJTOXPATHSTEP = 32;
  public int JJTXPATHAXISSPECIFIER = 33;
  public int JJTOXPATHAXISSPECIFIER = 34;
  public int JJTXPATHFORWARDAXISNAME = 35;
  public int JJTXPATHBACKWARDAXISNAME = 36;
  public int JJTOXPATHAXISNAME = 37;
  public int JJTXPATHABBREVIATEDAXISSPECIFIER = 38;
  public int JJTXPATHNODETEST = 39;
  public int JJTOXPATHNODETEST = 40;
  public int JJTOXPATHNODETESTOP = 41;
  public int JJTOXPATHNODETESTOPER = 42;
  public int JJTXPATHNAMETEST = 43;
  public int JJTXPATHQNAME = 44;
  public int JJTXPATHLITERAL = 45;
  public int JJTXPATHPREDICATE = 46;
  public int JJTOXPATHOPTIONALPREDICATE = 47;
  public int JJTXPATHPREDICATEEXPR = 48;
  public int JJTOXPATHPREDICATEEXPR = 49;
  public int JJTOXPATHACTION = 50;
  public int JJTOXPATHURLACTION = 51;
  public int JJTOXPATHUSERACTION = 52;
  public int JJTOXPATHACTIONPRED = 53;
  public int JJTOXPATHACTIONWAITPRED = 54;
  public int JJTOXPATHACTIONUNTILPRED = 55;
  public int JJTOXPATHABSOLUTEACTIONSIGNAL = 56;
  public int JJTUNGROUNDEDOXPATHACTIONDECLARATION = 57;
  public int JJTUNGROUNDEDOXPATHACTIONPOSITION = 58;
  public int JJTGROUNDEDOXPATHACTIONPOSITION = 59;
  public int JJTUNGROUNDEDOXPATHACTIONEXPLICIT = 60;
  public int JJTGROUNDEDOXPATHACTIONEXPLICIT = 61;
  public int JJTUNGROUNDEDOXPATHACTIONVARIABLE = 62;
  public int JJTOXPATHACTIONKEYWORD = 63;
  public int JJTOXPATHEXTRACTIONMARKER = 64;
  public int JJTOXPATHEXTRACTIONNAME = 65;
  public int JJTOXPATHEXTRACTIONVALUE = 66;
  public int JJTXPATHEXPR = 67;
  public int JJTXPATHOREXPR = 68;
  public int JJTXPATHANDEXPR = 69;
  public int JJTXPATHEQUALITYEXPR = 70;
  public int JJTXPATHEQUALITYEXPROP = 71;
  public int JJTXPATHRELATIONALEXPR = 72;
  public int JJTXPATHRELATIONALEXPROP = 73;
  public int JJTXPATHADDITIVEEXPR = 74;
  public int JJTXPATHADDITIVEEXPROP = 75;
  public int JJTXPATHMULTIPLICATIVEEXPR = 76;
  public int JJTXPATHMULTIPLICATIVEOP = 77;
  public int JJTXPATHUNARYEXPR = 78;
  public int JJTXPATHUNARYEXPROP = 79;
  public int JJTXPATHPRIMARYEXPR = 80;
  public int JJTXPATHNUMBER = 81;
  public int JJTXPATHFUNCTIONCALL = 82;
  public int JJTXPATHFUNCTIONCALLNAME = 83;
  public int JJTXPATHARGUMENT = 84;
  public int JJTXPATHUNIONEXPR = 85;
  public int JJTXPATHPATHEXPR = 86;
  public int JJTXPATHFILTEREXPR = 87;
  public int JJTABBREVIATEDABSOLUTEOXPATHLOCATIONPATH = 88;
  public int JJTABBREVIATEDSTEP = 89;
  public int JJTSCRAPEDECLARATION = 90;
  public int JJTSCRAPERNAME = 91;
  public int JJTSCRAPERPATH = 92;


  public String[] jjtNodeName = {
    "Script",
    "Declarations",
    "XQDeclarations",
    "void",
    "DatabaseFileName",
    "Letter",
    "URLName",
    "SupportedProtocols",
    "HostPort",
    "Host",
    "HostName",
    "URLIAlpha",
    "URLXAlphas",
    "URLXAlpha",
    "URLSafe",
    "URLExtra",
    "URLEscape",
    "HostNumber",
    "Digits",
    "Port",
    "URLPath",
    "URLSegment",
    "URLSearch",
    "VariableDeclaration",
    "VariableName",
    "PathDeclaration",
    "OXPathPathSegment",
    "RelativeOXPathLocationPath",
    "DescendantOrSelfShort",
    "OXPathKleeneStar",
    "OXPathKleeneStarPredicate",
    "OXPathKleeneStarPredicateArg",
    "OXPathStep",
    "XPathAxisSpecifier",
    "OXPathAxisSpecifier",
    "XPathForwardAxisName",
    "XPathBackwardAxisName",
    "OXPathAxisName",
    "XPathAbbreviatedAxisSpecifier",
    "XPathNodeTest",
    "OXPathNodeTest",
    "OXPathNodeTestOp",
    "OXPathNodeTestOper",
    "XPathNameTest",
    "XPathQName",
    "XPathLiteral",
    "XPathPredicate",
    "OXPathOptionalPredicate",
    "XPathPredicateExpr",
    "OXPathPredicateExpr",
    "OXPathAction",
    "OXPathURLAction",
    "OXPathUserAction",
    "OXPathActionPred",
    "OXPathActionWaitPred",
    "OXPathActionUntilPred",
    "OXPathAbsoluteActionSignal",
    "UnGroundedOXPathActionDeclaration",
    "UnGroundedOXPathActionPosition",
    "GroundedOXPathActionPosition",
    "UnGroundedOXPathActionExplicit",
    "GroundedOXPathActionExplicit",
    "UnGroundedOXPathActionVariable",
    "OXPathActionKeyword",
    "OXPathExtractionMarker",
    "OXPathExtractionName",
    "OXPathExtractionValue",
    "XPathExpr",
    "XPathOrExpr",
    "XPathAndExpr",
    "XPathEqualityExpr",
    "XPathEqualityExprOp",
    "XPathRelationalExpr",
    "XPathRelationalExprOp",
    "XPathAdditiveExpr",
    "XPathAdditiveExprOp",
    "XPathMultiplicativeExpr",
    "XPathMultiplicativeOp",
    "XPathUnaryExpr",
    "XPathUnaryExprOp",
    "XPathPrimaryExpr",
    "XPathNumber",
    "XPathFunctionCall",
    "XPathFunctionCallName",
    "XPathArgument",
    "XPathUnionExpr",
    "XPathPathExpr",
    "XPathFilterExpr",
    "AbbreviatedAbsoluteOXPathLocationPath",
    "AbbreviatedStep",
    "ScrapeDeclaration",
    "ScraperName",
    "ScraperPath",
  };
}
/* JavaCC - OriginalChecksum=401b171e0c5d3f5f1e97926b5e608994 (do not edit this line) */
