/* Generated By:JJTree&JavaCC: Do not edit this line. OXPathParserConstants.java */
package uk.ac.ox.comlab.diadem.oxpath.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface OXPathParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int APOSTROPHE_URL = 1;
  /** RegularExpression Id. */
  int QUOTE_URL = 2;
  /** RegularExpression Id. */
  int SPACE = 3;
  /** RegularExpression Id. */
  int TAB = 4;
  /** RegularExpression Id. */
  int NEWLINE = 5;
  /** RegularExpression Id. */
  int PROTOCOL = 6;
  /** RegularExpression Id. */
  int FOCUS = 7;
  /** RegularExpression Id. */
  int CLICK = 8;
  /** RegularExpression Id. */
  int DBLCLICK = 9;
  /** RegularExpression Id. */
  int MOUSEDOWN = 10;
  /** RegularExpression Id. */
  int MOUSEENTER = 11;
  /** RegularExpression Id. */
  int MOUSEMOVE = 12;
  /** RegularExpression Id. */
  int MOUSEOVER = 13;
  /** RegularExpression Id. */
  int MOUSEOUT = 14;
  /** RegularExpression Id. */
  int MOUSEUP = 15;
  /** RegularExpression Id. */
  int WHEEL = 16;
  /** RegularExpression Id. */
  int SUBMIT = 17;
  /** RegularExpression Id. */
  int CHECK = 18;
  /** RegularExpression Id. */
  int UNCHECK = 19;
  /** RegularExpression Id. */
  int END_URL_IN_PATH = 20;
  /** RegularExpression Id. */
  int END_URL = 21;
  /** RegularExpression Id. */
  int SLASH_URL = 22;
  /** RegularExpression Id. */
  int QUESTION_URL = 23;
  /** RegularExpression Id. */
  int MINUS_URL = 24;
  /** RegularExpression Id. */
  int UNDERSCORE_URL = 25;
  /** RegularExpression Id. */
  int PERIOD_URL = 26;
  /** RegularExpression Id. */
  int AMPERSAND_URL = 27;
  /** RegularExpression Id. */
  int EQUALS_URL = 28;
  /** RegularExpression Id. */
  int DOLLAR_URL = 29;
  /** RegularExpression Id. */
  int PERCENT_URL = 30;
  /** RegularExpression Id. */
  int AT_URL = 31;
  /** RegularExpression Id. */
  int PLUS_URL = 32;
  /** RegularExpression Id. */
  int EXCLAIMATION_URL = 33;
  /** RegularExpression Id. */
  int STAR_URL = 34;
  /** RegularExpression Id. */
  int OPEN_PARAN_URL = 35;
  /** RegularExpression Id. */
  int CLOSE_PARAN_URL = 36;
  /** RegularExpression Id. */
  int COMMA_URL = 37;
  /** RegularExpression Id. */
  int LOWER_ALPHA = 38;
  /** RegularExpression Id. */
  int UPPER_ALPHA = 39;
  /** RegularExpression Id. */
  int DIGIT = 40;
  /** RegularExpression Id. */
  int ENDLINE = 41;
  /** RegularExpression Id. */
  int EQUALS_DEFAULT = 42;
  /** RegularExpression Id. */
  int DOC_BEGIN = 43;
  /** RegularExpression Id. */
  int OPEN_PARAN = 44;
  /** RegularExpression Id. */
  int CLOSE_PARAN = 45;
  /** RegularExpression Id. */
  int OPEN_OPTIONAL = 46;
  /** RegularExpression Id. */
  int OPEN_BRACKET = 47;
  /** RegularExpression Id. */
  int CLOSE_BRACKET = 48;
  /** RegularExpression Id. */
  int BEGIN_URL_IN_PATH = 49;
  /** RegularExpression Id. */
  int OPEN_CURLY = 50;
  /** RegularExpression Id. */
  int CLOSE_CURLY = 51;
  /** RegularExpression Id. */
  int COMMA = 52;
  /** RegularExpression Id. */
  int NUMBER = 53;
  /** RegularExpression Id. */
  int DESCENDENT_OR_SELF_SHORT = 54;
  /** RegularExpression Id. */
  int BEGIN_USER_ACTION = 55;
  /** RegularExpression Id. */
  int BEGIN_KLEENE_STAR = 56;
  /** RegularExpression Id. */
  int BEGIN_BOUNDED_KLEENE_STAR_PRED = 57;
  /** RegularExpression Id. */
  int SLASH = 58;
  /** RegularExpression Id. */
  int BEGIN_EXTRACT_MARK = 59;
  /** RegularExpression Id. */
  int STYLE = 60;
  /** RegularExpression Id. */
  int ATTRIBUTE = 61;
  /** RegularExpression Id. */
  int CHILD = 62;
  /** RegularExpression Id. */
  int DESCENDANTORSELF = 63;
  /** RegularExpression Id. */
  int DESCENDANT = 64;
  /** RegularExpression Id. */
  int FOLLOWINGSIBLING = 65;
  /** RegularExpression Id. */
  int FOLLOWING = 66;
  /** RegularExpression Id. */
  int NAMESPACE = 67;
  /** RegularExpression Id. */
  int SELF = 68;
  /** RegularExpression Id. */
  int ANCESTORORSELF = 69;
  /** RegularExpression Id. */
  int ANCESTOR = 70;
  /** RegularExpression Id. */
  int PARENT = 71;
  /** RegularExpression Id. */
  int PRECEDINGSIBLING = 72;
  /** RegularExpression Id. */
  int PRECEDING = 73;
  /** RegularExpression Id. */
  int AXIS = 74;
  /** RegularExpression Id. */
  int COMMENT = 75;
  /** RegularExpression Id. */
  int TEXT = 76;
  /** RegularExpression Id. */
  int PROCESSING_INSTRUCTION = 77;
  /** RegularExpression Id. */
  int NODE = 78;
  /** RegularExpression Id. */
  int FIELD = 79;
  /** RegularExpression Id. */
  int ANY_FIELD = 80;
  /** RegularExpression Id. */
  int PERIOD = 81;
  /** RegularExpression Id. */
  int PARENT_SHORT = 82;
  /** RegularExpression Id. */
  int AT = 83;
  /** RegularExpression Id. */
  int POSITION = 84;
  /** RegularExpression Id. */
  int LAST = 85;
  /** RegularExpression Id. */
  int COUNT = 86;
  /** RegularExpression Id. */
  int ID = 87;
  /** RegularExpression Id. */
  int NAMESPACEURI = 88;
  /** RegularExpression Id. */
  int LOCALNAME = 89;
  /** RegularExpression Id. */
  int NAME = 90;
  /** RegularExpression Id. */
  int STRING = 91;
  /** RegularExpression Id. */
  int CONCAT = 92;
  /** RegularExpression Id. */
  int STARTSWITH = 93;
  /** RegularExpression Id. */
  int CONTAINSFUNC = 94;
  /** RegularExpression Id. */
  int SUBSTRINGBEFORE = 95;
  /** RegularExpression Id. */
  int SUBSTRINGAFTER = 96;
  /** RegularExpression Id. */
  int SUBSTRING = 97;
  /** RegularExpression Id. */
  int SUBSTRINGLENGTH = 98;
  /** RegularExpression Id. */
  int NORMALIZESPACE = 99;
  /** RegularExpression Id. */
  int TRANSLATE = 100;
  /** RegularExpression Id. */
  int BOOLEAN = 101;
  /** RegularExpression Id. */
  int NOT = 102;
  /** RegularExpression Id. */
  int TRUE = 103;
  /** RegularExpression Id. */
  int FALSE = 104;
  /** RegularExpression Id. */
  int LANG = 105;
  /** RegularExpression Id. */
  int NUMBERFUNC = 106;
  /** RegularExpression Id. */
  int SUM = 107;
  /** RegularExpression Id. */
  int FLOOR = 108;
  /** RegularExpression Id. */
  int CEILING = 109;
  /** RegularExpression Id. */
  int ROUND = 110;
  /** RegularExpression Id. */
  int VARIABLE = 111;
  /** RegularExpression Id. */
  int END_EXTRACT_MARK = 112;
  /** RegularExpression Id. */
  int NEGATIVE = 113;
  /** RegularExpression Id. */
  int AND = 114;
  /** RegularExpression Id. */
  int OR = 115;
  /** RegularExpression Id. */
  int MOD = 116;
  /** RegularExpression Id. */
  int DIV = 117;
  /** RegularExpression Id. */
  int MULTIPLY = 118;
  /** RegularExpression Id. */
  int UNION = 119;
  /** RegularExpression Id. */
  int PLUS = 120;
  /** RegularExpression Id. */
  int MINUS = 121;
  /** RegularExpression Id. */
  int LESSTE = 122;
  /** RegularExpression Id. */
  int LESS = 123;
  /** RegularExpression Id. */
  int GREATERTE = 124;
  /** RegularExpression Id. */
  int GREATER = 125;
  /** RegularExpression Id. */
  int NOTEQUAL = 126;
  /** RegularExpression Id. */
  int EQUALS = 127;
  /** RegularExpression Id. */
  int PERIOD_OP = 128;
  /** RegularExpression Id. */
  int HASH = 129;
  /** RegularExpression Id. */
  int WORD_TEST = 130;
  /** RegularExpression Id. */
  int CONTAINS = 131;
  /** RegularExpression Id. */
  int WAIT = 132;
  /** RegularExpression Id. */
  int UNTIL = 133;
  /** RegularExpression Id. */
  int DOLLAR = 134;
  /** RegularExpression Id. */
  int WILDCARD = 135;
  /** RegularExpression Id. */
  int NCNAME = 136;
  /** RegularExpression Id. */
  int NAMESTARTCHAR = 137;
  /** RegularExpression Id. */
  int COLON = 138;
  /** RegularExpression Id. */
  int DIGITS = 139;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE_STRING_PATH = 141;
  /** RegularExpression Id. */
  int SINGLE_QUOTE_STRING_PATH = 144;

  /** Lexical state. */
  int IN_URL = 0;
  /** Lexical state. */
  int DEFAULT = 1;
  /** Lexical state. */
  int IN_PATH_OP = 2;
  /** Lexical state. */
  int IN_DOUBLE_QUOTE_STRING_PATH = 3;
  /** Lexical state. */
  int IN_SINGLE_QUOTE_STRING_PATH = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\\'\"",
    "\"\\\"\"",
    "\" \"",
    "\"\\t\"",
    "<NEWLINE>",
    "<PROTOCOL>",
    "\"focus\"",
    "\"click\"",
    "\"dblclick\"",
    "\"mousedown\"",
    "\"mouseenter\"",
    "\"mousemove\"",
    "\"event\"",
    "\"mouseout\"",
    "\"mouseup\"",
    "\"wheel\"",
    "\"submit\"",
    "\"check\"",
    "\"uncheck\"",
    "\">\"",
    "\"}\"",
    "\"/\"",
    "\"?\"",
    "\"-\"",
    "\"_\"",
    "\".\"",
    "\"&\"",
    "\"=\"",
    "\"$\"",
    "\"%\"",
    "\"@\"",
    "\"+\"",
    "\"!\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<LOWER_ALPHA>",
    "<UPPER_ALPHA>",
    "<DIGIT>",
    "\";\"",
    "\"=\"",
    "<DOC_BEGIN>",
    "\"(\"",
    "\")\"",
    "\"[?\"",
    "\"[\"",
    "\"]\"",
    "<BEGIN_URL_IN_PATH>",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "<NUMBER>",
    "<DESCENDENT_OR_SELF_SHORT>",
    "<BEGIN_USER_ACTION>",
    "<BEGIN_KLEENE_STAR>",
    "<BEGIN_BOUNDED_KLEENE_STAR_PRED>",
    "\"/\"",
    "\":<\"",
    "<STYLE>",
    "<ATTRIBUTE>",
    "<CHILD>",
    "<DESCENDANTORSELF>",
    "<DESCENDANT>",
    "<FOLLOWINGSIBLING>",
    "<FOLLOWING>",
    "<NAMESPACE>",
    "<SELF>",
    "<ANCESTORORSELF>",
    "<ANCESTOR>",
    "<PARENT>",
    "<PRECEDINGSIBLING>",
    "<PRECEDING>",
    "\"::\"",
    "<COMMENT>",
    "<TEXT>",
    "<PROCESSING_INSTRUCTION>",
    "<NODE>",
    "<FIELD>",
    "<ANY_FIELD>",
    "\".\"",
    "\"..\"",
    "\"@\"",
    "<POSITION>",
    "<LAST>",
    "<COUNT>",
    "<ID>",
    "<NAMESPACEURI>",
    "<LOCALNAME>",
    "<NAME>",
    "<STRING>",
    "<CONCAT>",
    "<STARTSWITH>",
    "<CONTAINSFUNC>",
    "<SUBSTRINGBEFORE>",
    "<SUBSTRINGAFTER>",
    "<SUBSTRING>",
    "<SUBSTRINGLENGTH>",
    "<NORMALIZESPACE>",
    "<TRANSLATE>",
    "<BOOLEAN>",
    "<NOT>",
    "<TRUE>",
    "<FALSE>",
    "<LANG>",
    "<NUMBERFUNC>",
    "<SUM>",
    "<FLOOR>",
    "<CEILING>",
    "<ROUND>",
    "<VARIABLE>",
    "\">\"",
    "\"-\"",
    "\"and\"",
    "\"or\"",
    "\"mod\"",
    "\"div\"",
    "\"*\"",
    "\"|\"",
    "\"+\"",
    "\"-\"",
    "\"<=\"",
    "\"<\"",
    "\">=\"",
    "\">\"",
    "\"!=\"",
    "\"=\"",
    "\".\"",
    "\"#\"",
    "\"~=\"",
    "\"#=\"",
    "<WAIT>",
    "<UNTIL>",
    "\"$\"",
    "\"*\"",
    "<NCNAME>",
    "<NAMESTARTCHAR>",
    "\":\"",
    "<DIGITS>",
    "\"\\\"\"",
    "\"\\\"\"",
    "<token of kind 142>",
    "\"\\\'\"",
    "\"\\\'\"",
    "<token of kind 145>",
  };

}
