/* Generated By:JavaCC: Do not edit this line. OXPathParserVisitor.java Version 5.0 */
package uk.ac.ox.comlab.diadem.oxpath.parser.ast;

import uk.ac.ox.comlab.diadem.oxpath.parser.*;

public interface OXPathParserVisitor
{
  public Object visit(SimpleNode node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTExpression node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTRelativeOXPathLocationPath node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTSimpleOXPathStepPath node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTOXPathKleeneStarPath node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTOXPathActionPath node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTOXPathNodeTestOp node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTXPathLiteral node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTXPathPredicate node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTOXPathExtractionMarker node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTBinaryOpExpr node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTXPathUnaryExpr node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTXPathPrimaryExpr node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTXPathNumber node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTXPathFunctionCall node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
  public Object visit(ASTXPathPathExpr node, Object data) throws uk.ac.ox.comlab.diadem.oxpath.utils.OXPathException;
}
/* JavaCC - OriginalChecksum=34e12c42e9f0ae8d1ebfd148e40c6199 (do not edit this line) */
