/* Generated By:JavaCC: Do not edit this line. OXPathParserTreeConstants.java Version 5.0 */
package uk.ac.ox.comlab.diadem.oxpath.parser.ast;

import uk.ac.ox.comlab.diadem.oxpath.parser.*;

public interface OXPathParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTRELATIVEOXPATHLOCATIONPATH = 2;
  public int JJTSIMPLEOXPATHSTEPPATH = 3;
  public int JJTOXPATHKLEENESTARPATH = 4;
  public int JJTOXPATHACTIONPATH = 5;
  public int JJTOXPATHNODETESTOP = 6;
  public int JJTXPATHLITERAL = 7;
  public int JJTXPATHPREDICATE = 8;
  public int JJTOXPATHEXTRACTIONMARKER = 9;
  public int JJTBINARYOPEXPR = 10;
  public int JJTXPATHUNARYEXPR = 11;
  public int JJTXPATHPRIMARYEXPR = 12;
  public int JJTXPATHNUMBER = 13;
  public int JJTXPATHFUNCTIONCALL = 14;
  public int JJTXPATHPATHEXPR = 15;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "RelativeOXPathLocationPath",
    "SimpleOXPathStepPath",
    "OXPathKleeneStarPath",
    "OXPathActionPath",
    "OXPathNodeTestOp",
    "XPathLiteral",
    "XPathPredicate",
    "OXPathExtractionMarker",
    "BinaryOpExpr",
    "XPathUnaryExpr",
    "XPathPrimaryExpr",
    "XPathNumber",
    "XPathFunctionCall",
    "XPathPathExpr",
  };
}
/* JavaCC - OriginalChecksum=b958d93ec77d182756d9e10a81b4c44f (do not edit this line) */
